export { default as Close } from './Close';
export { default as Cry } from './Cry';
export { default as DefaultEyes } from './DefaultEyes';
export { default as Dizzy } from './Dizzy';
export { default as EyeRoll } from './EyeRoll';
export { default as Happy } from './Happy';
export { default as Hearts } from './Hearts';
export { default as Side } from './Side';
export { default as Squint } from './Squint';
export { default as Surprised } from './Surprised';
export { default as Wink } from './Wink';
export { default as WinkWacky } from './WinkWacky';
export { default as Eyes } from './Eyes';
export { default } from './Eyes';
