export { default as Concerned } from './Concerned';
export { default as Disbelief } from './Disbelief';
export { default as Eating } from './Eating';
export { default as Grimace } from './Grimace';
export { default as Sad } from './Sad';
export { default as ScreamOpen } from './ScreamOpen';
export { default as Serious } from './Serious';
export { default as Smile } from './Smile';
export { default as Tongue } from './Tongue';
export { default as Twinkle } from './Twinkle';
export { default as Vomit } from './Vomit';
export { default as DefaultMouth } from './DefaultMouth';
export { default } from './DefaultMouth';
