export { default as Angry } from './Angry';
export { default as AngryNatural } from './AngryNatural';
export { default as DefaultEyebrow } from './DefaultEyebrow';
export { default as DefaultNatural } from './DefaultNatural';
export { default as FlatNatural } from './FlatNatural';
export { default as FrownNatural } from './FrownNatural';
export { default as RaisedExcited } from './RaisedExcited';
export { default as RaisedExcitedNatural } from './RaisedExcitedNatural';
export { default as SadConcerned } from './SadConcerned';
export { default as SadConcernedNatural } from './SadConcernedNatural';
export { default as UnibrowNatural } from './UnibrowNatural';
export { default as UpDown } from './UpDown';
export { default as UpDownNatural } from './UpDownNatural';
export { default as Eyebrows } from './Eyebrows';
export { default } from './Eyebrows';
